### ISSUE TITLE
[Bug]Sell from stack

### ISSUE THREAD

**Issue by moepi2k** [insthync/UnityMultiplayerARPG_AuctionHouse#1]
when someone have a itemstack of e.g 5 and put only 1/5 from it in ah. it reduces 1.
but the one who buy it receive all 5

https://gyazo.com/d2e2459c025f90a7fd5855536dce2344

may the issue is in that part ?
https://gyazo.com/42d8d47ede0216d426e7c834ae1d821a

it reduce the right amount from inventory, but when item will add to bidding list it dont check for set amount, it just take the wohle stack

**Comment by Callepo** [comment]
@insthync since we on topic, this is not a bug, but having a Bid Cancel option would be nice, for example if i sell a Weapon. and i accidently put it up wrong price, there is no way to fix the price or remove it from the auction, basically u have to w8 till the time is over. 

Dont need edit, but Cancel would be very good
Like ability to cancel ur auction if no one already placed a bid to buy it. so if u make mistake and ur fast u can always change it.
just an FYI.

**Comment by insthync** [comment]
@moepi2k Yes that is it, sorry for slow response, I just see this. 

You actually can try to fix it then when you fix it, you can create pull request to request me to pull your codes changes to the project.

* * *
@Callepo  Okay, I will add it.
